version: "3.8"

services:
  redis:
    container_name: "redis"
    image: redis:alpine
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports: 
      - "6379:6379"
    # map the volumes to that redis has the custom conf file from this project.
    volumes: 
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  # redis:
  #   image: redis:6.0
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass mypassword
    # volumes: 
    #   - redis:/data

  # redis:
  #   container_name: redis
  #   image: redis:alpine
  #   ports: 
  #   - "6379:6379"
  #   command: ["redis-server", "--bind", "redis", "--port", "6379"]
  app:
    container_name: app
    image : meinanto/redis-test:latest
    build: 
      context: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - redis
    # links:
    #   - redis
  